# Generated by Django 5.0.7 on 2024-07-13 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('max_fine', models.IntegerField()),
                ('max_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50, null=True)),
                ('license', models.CharField(max_length=16, null=True, unique=True)),
                ('dob', models.DateField(null=True, verbose_name='date of birth')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('plate_number', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('report', models.CharField(max_length=500)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('offense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.offense')),
                ('ownership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.ownership')),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.people')),
            ],
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('points', models.IntegerField()),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.incident')),
            ],
        ),
        migrations.AddField(
            model_name='ownership',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.people'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.vehicle'),
        ),
    ]
