# Generated by Django 5.0.7 on 2024-07-13 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fines',
            new_name='Fine',
        ),
        migrations.AlterField(
            model_name='incident',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.ownership'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.people'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.people'),
        ),
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='people',
            name='license',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
