# Generated by Django 5.0.7 on 2024-07-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_fines_fine_alter_incident_ownership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='license',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
