# Generated by Django 5.0.7 on 2024-07-16 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_people_license_alter_vehicle_plate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='people',
        ),
        migrations.AlterField(
            model_name='ownership',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.vehicle'),
        ),
    ]
