# Generated by Django 5.0.7 on 2024-07-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_incident_people_alter_ownership_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='license',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
