# Generated by Django 5.0.7 on 2024-07-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_people_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='creator',
        ),
    ]
